import type { CatalogResponse } from '../catalog/contracts';

export const FRONTEND_TEST_CATALOG: CatalogResponse = {
  revision: 'test-revision',
  publishedAt: '2026-08-03T00:00:00.000Z',
  freshness: { status: 'fresh', checkedAt: '2026-08-03T01:00:00.000Z' },
  provenance: [
    {
      id: 'provider-a-subscription',
      providerId: 'provider-a',
      sourceUrl: 'https://provider.example/pricing',
      observedAt: '2026-08-03T00:00:00.000Z',
      sourceKind: 'manual_manifest',
      confidence: 'manual_verified',
    },
    {
      id: 'provider-a-direct',
      providerId: 'provider-a',
      sourceUrl: 'https://provider.example/api-pricing',
      observedAt: '2026-08-03T00:00:00.000Z',
      sourceKind: 'official_json',
      confidence: 'official',
    },
    {
      id: 'openrouter-models',
      providerId: 'openrouter',
      sourceUrl: 'https://openrouter.ai/models',
      observedAt: '2026-08-03T00:00:00.000Z',
      sourceKind: 'official_json',
      confidence: 'official',
    },
    {
      id: 'opencode-zen',
      providerId: 'opencode',
      sourceUrl: 'https://opencode.ai/docs/zen',
      observedAt: '2026-08-03T00:00:00.000Z',
      sourceKind: 'official_json',
      confidence: 'official',
    },
  ],
  plans: [
    {
      id: 'provider-a:starter',
      providerId: 'provider-a',
      displayName: 'Starter',
      monthlyCostMicroDollars: 20_000_000,
      currency: 'USD',
      pricingBasis: 'subscription',
      route: 'subscription',
      entitlement: { kind: 'rolling_limit', description: 'Usage varies with demand.' },
      sourceId: 'provider-a-subscription',
    },
    {
      id: 'provider-a:fixed',
      providerId: 'provider-a',
      displayName: 'Fixed 10M',
      monthlyCostMicroDollars: 40_000_000,
      currency: 'USD',
      pricingBasis: 'subscription',
      route: 'subscription',
      entitlement: { kind: 'fixed_tokens', monthlyTokens: 10_000_000 },
      sourceId: 'provider-a-subscription',
    },
  ],
  modelOffers: [
    {
      id: 'provider-a:alpha:direct_provider',
      providerId: 'provider-a',
      displayName: 'Alpha Direct',
      modelId: 'alpha',
      pricingBasis: 'direct_provider_api',
      route: 'direct_provider',
      currency: 'USD',
      unit: 'micro_dollars_per_million_tokens',
      inputMicroDollarsPerMillion: 2_000_000,
      outputMicroDollarsPerMillion: 8_000_000,
      sourceId: 'provider-a-direct',
    },
    {
      id: 'provider-a:alpha:openrouter',
      providerId: 'provider-a',
      displayName: 'Alpha via OpenRouter',
      modelId: 'alpha',
      pricingBasis: 'openrouter',
      route: 'openrouter',
      currency: 'USD',
      unit: 'micro_dollars_per_million_tokens',
      inputMicroDollarsPerMillion: 2_500_000,
      outputMicroDollarsPerMillion: 9_000_000,
      sourceId: 'openrouter-models',
    },
    {
      id: 'provider-a:alpha:opencode_zen',
      providerId: 'provider-a',
      displayName: 'Alpha via OpenCode Zen',
      modelId: 'alpha',
      pricingBasis: 'opencode_zen',
      route: 'opencode_zen',
      currency: 'USD',
      unit: 'micro_dollars_per_million_tokens',
      inputMicroDollarsPerMillion: 1_000_000,
      outputMicroDollarsPerMillion: 4_000_000,
      sourceId: 'opencode-zen',
    },
  ],
};
