const TB={charts:[],weights:{agentic:20,coding:20,reasoning:20,math:15,multimodal:15,throughput:10},selected:[],theme:localStorage.tbTheme||'light'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function domainScore(m,key){return key==='throughput'?Math.min(100,m.tps/120*100):m[key]}
function score(m,w=TB.weights){let sum=Object.values(w).reduce((a,b)=>a+b,0);return sum?Object.entries(w).reduce((n,[k,v])=>n+domainScore(m,k)*v,0)/sum:null}
function colors(){let d=document.documentElement.dataset.theme==='dark';return{ink:d?'#f8fafc':'#0f172a',muted:d?'#cbd5e1':'#475569',line:d?'#334155':'#e2e8f0',plum:d?'#e879f9':'#741a66'}}
function chart(canvas,config){if(!canvas)return null;if(typeof Chart==='undefined'){canvas.hidden=true;if(!canvas.parentElement.querySelector('.chart-failure'))canvas.insertAdjacentHTML('afterend','<p class="empty chart-failure" role="status">Chart.js did not load. Use the exact evidence table on this page.</p>');return null}canvas.hidden=false;canvas.parentElement.querySelector('.chart-failure')?.remove();let old=Chart.getChart(canvas);if(old)old.destroy();config.options={responsive:true,maintainAspectRatio:false,animation:matchMedia('(prefers-reduced-motion: reduce)').matches?false:{duration:250},...config.options};return new Chart(canvas,config)}
function setupShell(){document.documentElement.dataset.theme=TB.theme;let current=location.pathname.split('/').pop()||'index.html',theme=$('#theme'),nav=$('.nav'),modelPages=['index.html','model-profile.html','model-lifecycle.html'];let navItems=[{label:'Home',pending:true},{label:'Models',href:'index.html#catalog',active:modelPages.includes(current)},{label:'Leaderboards',href:'custom-leaderboard.html',active:current==='custom-leaderboard.html'},{label:'Compare',pending:true},{label:'Subscribe vs API',pending:true},{label:'Articles',href:'article-hybrid-router.html',active:current==='article-hybrid-router.html'}];if(nav)nav.innerHTML=navItems.map(item=>item.pending?`<span class="nav-pending" aria-disabled="true" title="Not included in this proof batch">${item.label}</span>`:`<a href="${item.href}"${item.active?' aria-current="page"':''}>${item.label}</a>`).join('');if(current==='article-hybrid-router.html'){let metadata=$('article header .label'),fixture=$('article header .fixture');if(metadata)metadata.textContent='Guide · Published 12 Aug 2026 · Updated 15 Aug 2026 · Review status: current';if(fixture&&!$('#article-evidence-cue'))fixture.insertAdjacentHTML('afterend','<p id="article-evidence-cue" class="fixture">Evidence cue · route-price and SLA fixtures observed 15 Aug 2026 · sources itemized below</p>')}if(theme){let syncTheme=()=>{let dark=TB.theme==='dark';theme.textContent='Theme';theme.setAttribute('aria-pressed',String(dark));theme.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme')};syncTheme();theme.addEventListener('click',()=>{TB.theme=TB.theme==='dark'?'light':'dark';localStorage.tbTheme=TB.theme;document.documentElement.dataset.theme=TB.theme;syncTheme();window.renderPage?.()})}}
const baseShellSetup=setupShell;setupShell=function(){baseShellSetup();if(location.pathname.endsWith('article-hybrid-router.html')&&!$('#mobile-toc')){let header=$('article header');header?.insertAdjacentHTML('afterend','<details id="mobile-toc" class="mobile-toc panel soft"><summary>On this page</summary><nav aria-label="Article sections"><a href="#question">Decision question</a><a href="#recommendation">Recommendation</a><a href="#assumptions">Assumptions</a><a href="#evidence">Evidence framing</a><a href="#cost">Cost comparison</a><a href="#matrix">Decision matrix</a><a href="#next">Internal tools</a></nav></details>')}};function link(m){return `<a class="model-name" href="model-profile.html?model=${encodeURIComponent(m.id)}">${m.name}</a>`}
function modelOptions(){return TB_MODELS.map(m=>`<option value="${m.id}">${m.name} — ${m.provider}</option>`).join('')}
function radar(canvas,models){let c=colors(),keys=['agentic','coding','reasoning','math','multimodal','throughput'];return chart(canvas,{type:'radar',data:{labels:['Agentic','Coding','Reasoning','Math','Multimodal','Throughput'],datasets:models.map((m,i)=>({label:m.name,data:keys.map(k=>domainScore(m,k)),borderColor:[m.color,c.plum,'#f97316'][i],backgroundColor:([m.color,c.plum,'#f97316'][i])+'26',borderWidth:2}))},options:{plugins:{legend:{labels:{color:c.muted,font:{size:11}}}},scales:{r:{min:45,max:100,ticks:{display:false},grid:{color:c.line},angleLines:{color:c.line},pointLabels:{color:c.muted,font:{size:10}}}}}})}
function table(models){return `<div class="table-wrap" role="region" aria-label="Ranked model evidence" tabindex="0"><table><thead><tr><th>Rank</th><th>Model / profile</th><th>Provider</th><th>Composite</th><th>Blended $/1M</th><th>TTFT</th><th>Throughput</th><th>Lifecycle</th><th>Compare</th></tr></thead><tbody>${models.map((m,i)=>`<tr><td>${i+1}</td><td>${link(m)}</td><td><span class="provider-dot" style="background:${m.color}"></span>${m.provider}</td><td>${score(m).toFixed(1)}</td><td>$${m.cost.toFixed(2)}</td><td>${m.ttft}s</td><td>${m.tps} tok/s</td><td>${m.lifecycle||'Not reported'}</td><td><button class="toggle compare" aria-pressed="${TB.selected.includes(m.id)}" data-id="${m.id}">${TB.selected.includes(m.id)?'Selected':'Compare'}</button></td></tr>`).join('')}</tbody></table></div>`}
const compareRoots=new WeakSet();function bindCompare(root=document){if(compareRoots.has(root))return;compareRoots.add(root);root.addEventListener('click',event=>{let b=event.target.closest?.('.compare');if(!b||!root.contains(b))return;let id=b.dataset.id,target=root===document?document.body:root;$('.compare-limit',target)?.remove();if(TB.selected.includes(id)){TB.selected=TB.selected.filter(x=>x!==id)}else if(TB.selected.length<3){TB.selected.push(id)}else{target.insertAdjacentHTML('afterbegin','<p class="error compare-limit" role="status">Comparison is limited to three models. Remove one selected model before adding another.</p>');return}window.renderPage?.()})}
window.TB={...TB,$,$$,domainScore,score,colors,chart,setupShell,link,modelOptions,radar,table,bindCompare};
document.head.append(Object.assign(document.createElement('style'),{textContent:'@media(max-width:800px){.nav{width:calc(100vw - 1px);max-width:calc(100vw - 1px);box-sizing:border-box;overflow-x:auto;contain:layout paint;justify-content:flex-start}.nav a{flex:0 0 auto}}'}));
